{% set version = "2.11" %}

package:
  name: pyicu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyICU/PyICU-{{ version }}.tar.gz
  sha256: 3ab531264cfe9132b3d2ac5d708da9a4649d25f6e6813730ac88cf040a08a844

build:
  number: 1
  skip: True  # [win]
  script: 
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - icu {{ icu }}
    - setuptools
    - wheel
  run:
    - python
    - icu

test:
  imports:
    - icu
  commands:
    - pip check
    - python -c "from icu import Locale;locale = Locale('pt_BR')"
  requires:
    - pip

about:
  home: https://gitlab.pyicu.org/main/pyicu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.

  description: |
    Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
    ICU stands for "International Components for Unicode". These are the i18n
    libraries of the Unicode Consortium. They implement much of the Unicode Standard,
    many of its companion Unicode Technical Standards, and much of Unicode CLDR.
  doc_url: https://gitlab.pyicu.org/main/pyicu/-/blob/main/README.md
  dev_url: https://gitlab.pyicu.org/main/pyicu

extra:
  recipe-maintainers:
    - cu8blank
