{% set version = "2.16.2" %}

package:
  name: pyicu
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyicu/pyicu-{{ version }}.tar.gz
  sha256: 006d51e24b5ec76df6ec2130f3dde269c51db8b8cfebb7d45a427dde0d10aa52
  patches:
    - 0001-fix-macos-AnnualTimeZoneRule-MAX_YEAR-symbol.patch  # [osx]

build:
  number: 0
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - icu 78
    - setuptools
    - wheel
  run:
    - python
    - icu

test:
  source_files:
    - test
  imports:
    - icu
  commands:
    - pip check
    - python -c "from icu import Locale;locale = Locale('pt_BR')"
    - pytest -ra -v test
  requires:
    - pip
    - pytest
    - six

about:
  home: https://gitlab.pyicu.org/main/pyicu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.

  description: |
    Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
    ICU stands for "International Components for Unicode". These are the i18n
    libraries of the Unicode Consortium. They implement much of the Unicode Standard,
    many of its companion Unicode Technical Standards, and much of Unicode CLDR.
  doc_url: https://gitlab.pyicu.org/main/pyicu/-/blob/main/README.md
  dev_url: https://gitlab.pyicu.org/main/pyicu

extra:
  recipe-maintainers:
    - cu8blank
