travis:
  secure:
    BINSTAR_TOKEN: FccowX670wD/gF8XGB9dod6zHnxkfH5aEtLhZK9Z6yKe+tA4GL9bhrWQL4hBMpi28dd7Wl7f8Jx1Siozrpec+S+3UMH/DU85kJlCytApOd+bnjid1/ft8dWJAyEm+SmDbbJ5g/GMv/ROxkBhjTkG1fXYFAyWsTR+2rFcjdRxJUPRMEHGSP6MUfja4BtLl2vNoRGjT3RX+dUdhay7YecGm9DPRKHZUsfZyf88FFCONrZoGxqogXbOeTMBddbpOZsuno6kCjSPZrR0WneHsaXZ3dZRt7hxj3+74/uxmPKm0OaEpp5xYYsKDRMXLZuPILS5LfRnYQAST3pporMmeCwGysMs/Fc4Jnjm20siyEFIr07v8x99IbUKJaqxEvu7bl/XkaS0sKvgaCpgNMPYOPMVW0n66+exGj30GkYcKq0XUUr04Po7YaqMCz0firDvsOJv/veiWegua5P56fhW2HLQk50wSoiuMPa+GKONCZ3gwHTrjeta/oi1XRkQPTYwpqcWLheLbLpxAGDt4ByvAYKb7SiyuAR2BkKmfMMKL3ZIGCLB2/UkIGIZDy9cwg7xkxrRsxIv9T7Al7cT8eMTWUh7BQbVWRLlAKdqCNblgoEsxAbEXdZwj37ZieCWiKabqlmIXtqgSlLktSKp9MHEubfLzBVEiPuQ3jDMlPcP4qDlI0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
