travis:
  secure:
    BINSTAR_TOKEN: YZURQq6NwMfPmIobFJMXYkAZ258IfjmdFn2mrBbysFZdVycsq+Kae0vmki5Wd9EMhLCC0p/R1e9Wk2Y+nEFICgAQbnuMZMKqJ3QsksMLSjvVq05SYe3aRi+W9fKMErjw5r2+dPO9hS6IBmk9NkqHOt3RflsnvhvTSsJtFs55n+I2/l0wdNIPJujY/DKQ1PxW3aH6QmUrlWJB4sk1XzALD7w8yXzfQsFG4uTQXMtlbXPQARajT82pEsMdw986iKkJZgskLblffIv1D7W+oQdPhwBPZem8NRqcjVsid1kdtUA3SHs0w4qOjeX/sIGAb85MDnhPzj4WGCoEQ2dixJwPrlGbc1SRiude//wWZSHY9C7FzTBoUslAyJ6RHdyaXYyrzMayEqCTqOFV9YcKX3ANTgx+WPvFVmnVOTn9a/pgeUfcAWQZlvy55/++3/Mhc54QPP899ZAlscfgKAOF3NQZh7+H4fGANTX05YghP296+BOOMdKz5GpmLO7n2/GgTixA9o4ujfpAVc/76E9mTJEJ/Wd7reKhtlT5zKLiI36A+dhjF05wTXEghLkSCugoZDwhgYtHQ4tkU4A/vf+spUyCXi3vnVyW1nU/YgCMY/2BdiH5TSiX+UbIIbcNK7ylQ+LakcqJEvO9YxepEGqcXevlaOnI8YyHGTTFVmFBDmEZgqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
