travis:
  secure:
    BINSTAR_TOKEN: GbpjbbBrll6lNp8vKSkwfXDYyuIGuryhSuVJVS9UOCoKTnWnt51Jimcs524yze7phLL2rr4RoqkzyJGOT7V1CLwalQ0zvIIZ5yQjydvOZBUNExZrm1aOfVCnOWUS8VOwk2LE0YKGeqGr5Md4+iXRfgsiV/5iuxPggdaXwPUuNCqh0Pz+ylXqXl8UaB5V1XrUg/D8CtZy3uefpiOQzhkEtoSAQnR8w9VB5g2APYG1GBs53ZLUz1aX6OT5VLxa70daoUivjTtTqcKLQr79latyCAefvgDfY5A1MEKXqj/dkc9DMFsgXAkvsAsdFHUC5ewn5d16Q9XJjJIrXKUi7jCCdm27wzblRLLTqaBYgxyg86OgnnYTb/xRf9Ed/A8K+7+Db3uHntWzMtOMNxTtWyqSumHZu+d2nEDzvDksbOBixKtnZoewz/B8jLaTJuivR5VBw/VhDdWSr8WU/cx1arg372oLtkNFLXcZCk/oBVd3lAEhHnR3W2VZtfxa/GL3N0SIq6PlRYWE+AOXh8Lyn5yA8vHolxy6MdNxZKWfPawXHn3a8QsdxoaAatmwrWMUdz69lhx0zWQ8yWARd1Mt7MrYYQ+x0DTmP89JRRyNMNXzhLrpXUcL82uTXwIqHXjXJAYNj6EWG0sStriM2qXj3lslxvCmNfIdt2Vt6V07Rln/qvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
